name: Sync to Notion
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: franchecol/obsidian-to-notion-action@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-page-id: "321daeb71f528031b649d4424ebd279b"
          source-dir: "."
